#!/usr/bin/env bash
# A Bash script that kills the 4-to_infinity_and_beyond process

# Find the PID(s) of the running 4-to_infinity_and_beyond script
PID=$(pgrep -f 4-to_infinity_and_beyond)

# Kill the process if it exists
if [ -n "$PID" ]; then
    kill "$PID"
fi
