#!/usr/bin/env bash
# 7-highlander: Infinite loop that handles SIGTERM

# Trap SIGTERM and print "I am invincible!!!" instead of terminating
trap 'echo "I am invincible!!!"' SIGTERM

# Infinite loop
while true; do
    echo "To infinity and beyond"
    sleep 2
done
